### PR TITLE
Properly load config from $WAKATIME_HOME/.wakatime.cfg

### LINKED ISSUE #94: atom-wakatime does not respect WAKATIME_HOME
1. In working around #90, I set the `WAKATIME_HOME` environment variable to a directory like `$HOME/.local/share/wakatime`. At the same time, I moved `.wakatime.cfg`, `.wakatime.db`, `.wakatime.log` into this directory.
2. When I next started Atom, I saw an error message that my API key was not found.
3. In the Atom settings view, I re-entered my API key.
4. I noticed the file `$HOME/.wakatime.cfg` was created, while `$WAKATIME_HOME/.wakatime.cfg` was not modified.

It seems that when atom-wakatime invokes the wakatime Python core, the latter correctly picks up `WAKATIME_HOME`, so that the .db and .log files are modified in the correct directory. But the Atom plugin reads and writes the .cfg file in the wrong place. [Searching the code in this repo](https://github.com/wakatime/atom-wakatime/search?q=WAKATIME_HOME) shows that the environment variable is not used.

For now I work around this issue with a symlink:
```
$ ln -s $HOME/.local/share/wakatime/.wakatime.cfg $HOME/.wakatime.cfg
```

### PR DESCRIPTION
**Pull request by ein-stein-chen**
This adapts the behaviour of this plugin to the one of the wakatime cli as documented in
https://github.com/wakatime/wakatime/blob/master/README.rst#configuring

As we fallback to the home directory if $WAKATIME_HOME is not present this is
not a backward incompatible change.

Fixes #94

### CODE REVIEW

File: lib/wakatime.coffee [hunk 1]
```diff
@@ -371,10 +371,6 @@ sendHeartbeat = (file, lineno, isWrite) ->
     if atom.config.get 'wakatime.disableSSLCertVerify'
       args.push('--no-ssl-verify')
 
-    # fix for wakatime/atom-wakatime#65
```
Comment (alanhamlett) [inline lib/wakatime.coffee]: We still need to pass `--config` to `wakatime-cli` because sometimes it can't find the config file on it's own.
